# Generated by Django 3.1.4 on 2021-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210120_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email-адреса'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
    ]
