# Generated by Django 3.1.4 on 2021-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210120_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email-адреса'),
        ),
    ]
