# Generated by Django 3.1.4 on 2021-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210120_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
