# Generated by Django 3.1.4 on 2021-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210124_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='f_name',
            field=models.CharField(max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='order',
            name='l_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Прізвище'),
        ),
    ]
